title: Site

tabs:
  content:
    columns:
      - width: 1/2
        fields:
          announcement:
            type: textarea
            label: Announcement
          phonetimes:
            type: structure
            label: Telefontider
            fields:
              day:
                type: date
                width: 1/4
              from:
                type: number
                default: 10
                width: 1/4
              to:
                type: number
                default: 12
                width: 1/4
          quotes:
            type: structure
            label: Quotes
            fields:
              text:
                type: text
                default: '"Citat" — Kunstner, Titel(eller årstal)'
      - width: 1/2
        sections:
          pages:
            type: pages
            sortable: true
            delete: false
          team: sections/team

